name: Rust

on:
  push:
    branches: dev
  pull_request:
    branches: dev

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        features: ["--no-default-features", "--all-features"]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Build
        run: cargo build --verbose ${{ matrix.features }}
      - name: Run tests
        run: cargo test --verbose ${{ matrix.features }}
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
