name: build

on:
  push:
    branches: dev
  pull_request:
    branches: dev

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy
      - name: Check without features
        run: cargo check --verbose --no-default-features
      - name: Build with features
        run: cargo build --verbose --all-features
        # bevy is only a dev-dependency, which is why we do this after cargo build.
        # the bevy_* crates we use for cargo build do not require these dependencies.
      - name: Install dependencies needed by bevy
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
      - name: Run tests
        run: cargo test --verbose --all-features
      - name: Clippy
        run: cargo clippy -- -Dwarnings
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
