name: Rust

on:
  push:
    branches: dev
  pull_request:
    branches: dev

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Check without features
        run: cargo check --verbose --no-default-features
      - name: Build with features
        run: cargo build --verbose --all-features
      - name: Run tests
        run: cargo test --verbose --all-features
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
      - name: Generate readme
        run: |
          cargo install cargo-readme
          cargo readme > README2.md
      - name: Check readme is up to date
        run: diff README.md README2.md
